-- CreateEnum
CREATE TYPE "LifeStage" AS ENUM ('EARLY_CAREER', 'MID_CAREER', 'PRE_RETIREMENT', 'RETIRED');

-- CreateEnum
CREATE TYPE "Industry" AS ENUM ('HEALTHCARE', 'TECHNOLOGY', 'GOVERNMENT', 'EDUCATION', 'RETAIL_SERVICE', 'CONSTRUCTION_TRADES', 'FINANCE_BANKING', 'LOGISTICS_TRANSPORTATION', 'ENERGY', 'AGRICULTURE', 'CREATIVE_MEDIA', 'RESEARCH_NONPROFIT', 'OTHER', 'NOT_APPLICABLE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "debtTypes" TEXT[],
ADD COLUMN     "industry" "Industry",
ADD COLUMN     "lifeStage" "LifeStage";
